version: '3'
services:
  web:
    build: .
    container_name: react-app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

# 最初
# version: '3'
# services:
#   web:
#     build: .
#     container_name: react-app-container
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#     command: sh
#     tty: true 